recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 50
  constrain_similarities: true
- name: EntitySynonymMapper

policies: []
assistant_id: 20260205-154414-approximate-waterfall
